<?php
/**
 * GetAllOutputKeysTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FireboostIO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fireboost-stage.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FireboostIO\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetAllOutputKeysTest Class Doc Comment
 *
 * @category    Class
 * @description GetAllOutputKeys
 * @package     FireboostIO
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetAllOutputKeysTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetAllOutputKeys"
     */
    public function testGetAllOutputKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_public"
     */
    public function testPropertyIsPublic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cache_key"
     */
    public function testPropertyCacheKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
