<?php
/**
 * InlineResponse200DataTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FireboostIO
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Fireboost.io
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FireboostIO\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse200DataTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200Data
 * @package     FireboostIO
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse200DataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse200Data"
     */
    public function testInlineResponse200Data()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statistic_data"
     */
    public function testPropertyStatisticData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
